# Generated by Django 3.1 on 2020-10-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201003_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='ciudad',
        ),
    ]
