# Generated by Django 3.1 on 2020-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_datos_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='profesion',
            name='servicio',
            field=models.ManyToManyField(null=True, to='api.Servicio'),
        ),
    ]
