# Generated by Django 3.1 on 2020-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201012_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesion',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
