# Generated by Django 3.1 on 2020-10-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profesion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_expiracion',
            field=models.DateField(),
        ),
    ]
