# Generated by Django 3.1 on 2020-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201012_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='altitud',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
