# Generated by Django 3.1 on 2020-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201013_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='altitud',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
