# Generated by Django 3.1 on 2020-10-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_datos_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='proveedores',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.CreateModel(
            name='Envio_Interesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.solicitud')),
            ],
        ),
    ]
