# Generated by Django 3.1 on 2020-10-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201025_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio_interesados',
            name='oferta',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
