# Generated by Django 3.1 on 2020-10-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201027_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_interesados',
            name='oferta',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
