# Generated by Django 3.1 on 2020-10-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201027_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_interesados',
            name='oferta',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
