# Generated by Django 3.1 on 2020-10-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201027_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='foto_ubicacion',
            field=models.ImageField(blank=True, null=True, upload_to='foto_solicitud/foto_ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='referencia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
