# Generated by Django 3.1 on 2020-11-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201028_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cedula',
            field=models.CharField(default='0999999999', max_length=20, null=True),
        ),
    ]
