# Generated by Django 3.1 on 2020-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_document_proveedor_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='document',
            field=models.ManyToManyField(null=True, to='api.Document'),
        ),
        migrations.DeleteModel(
            name='Proveedor_Documents',
        ),
    ]
