# Generated by Django 3.1 on 2020-11-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201103_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor_Pendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('profesion', models.CharField(max_length=255)),
                ('banco', models.CharField(max_length=255, null=True)),
                ('tipo_cuenta', models.CharField(max_length=255, null=True)),
                ('cuenta', models.CharField(max_length=255, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('document', models.ManyToManyField(null=True, to='api.Document')),
                ('user_datos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.datos')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.banco')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
                ('tipo_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipo_cuenta')),
            ],
        ),
    ]
