# Generated by Django 3.1 on 2020-11-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_banco_cuenta_proveedor_pendiente_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(default='0999999999', max_length=25),
        ),
    ]
