# Generated by Django 3.1 on 2020-11-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_cuenta_numero_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor_pendiente',
            old_name='descripcion',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='document',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='tipo_cuenta',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='user_datos',
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
