# Generated by Django 3.1 on 2020-11-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201103_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='ano_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='profesion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
