# Generated by Django 3.1 on 2020-11-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201103_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documento',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='banco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='numero_cuenta',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='tipo_cuenta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
