# Generated by Django 3.1 on 2020-11-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201105_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
