# Generated by Django 3.1 on 2020-11-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20201105_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='foto_descripcion',
            field=models.ImageField(blank=True, null=True, upload_to='foto_solicitud/foto_descripcion'),
        ),
    ]
