# Generated by Django 3.1 on 2020-11-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='security_access',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
