# Generated by Django 3.1 on 2020-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_datos_security_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
