# Generated by Django 3.1 on 2020-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_proveedor_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='adjudicar',
            field=models.BooleanField(default=False),
        ),
    ]
