# Generated by Django 3.1 on 2020-11-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
