# Generated by Django 3.1 on 2020-11-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20201126_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='solicitante',
        ),
        migrations.CreateModel(
            name='Tarjeta_Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitante')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta')),
            ],
        ),
    ]
