# Generated by Django 3.1 on 2020-11-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20201126_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
