# Generated by Django 3.1 on 2020-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_tarjeta_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta_solicitante',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
