# Generated by Django 3.1 on 2020-11-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_tarjeta_solicitante_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.solicitante'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tarjeta_Solicitante',
        ),
    ]
