# Generated by Django 3.1 on 2020-11-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20201128_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
