# Generated by Django 3.1 on 2020-11-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20201129_0333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
