# Generated by Django 3.1 on 2020-12-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_notificaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaciones',
            new_name='Notificacion',
        ),
    ]
