# Generated by Django 3.1 on 2020-12-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20201208_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='ruta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
