# Generated by Django 3.1 on 2020-12-09 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0055_auto_20201208_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='user_datos',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
