# Generated by Django 3.1 on 2021-01-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_proveedor_pendiente_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='documento',
        ),
    ]
