# Generated by Django 3.1 on 2021-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_proveedor_pendiente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
