# Generated by Django 3.1 on 2021-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20210122_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='termino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
