# Generated by Django 3.1 on 2021-01-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_promocion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
