# Generated by Django 3.1 on 2021-01-28 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_promocion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='participantes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PromocionCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promocion')),
            ],
        ),
    ]
