# Generated by Django 3.1 on 2021-01-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_codigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
