# Generated by Django 3.1 on 2021-01-29 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0068_auto_20210128_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('impuesto', models.IntegerField()),
                ('referencia', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promocion')),
                ('tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('impuesto', models.IntegerField()),
                ('referencia', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promocion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
