# Generated by Django 3.1 on 2021-01-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_solicitud_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoefectivo',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.solicitud'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.solicitud'),
        ),
    ]
