# Generated by Django 3.1 on 2021-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20210129_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoefectivo',
            name='impuesto',
        ),
    ]
