# Generated by Django 3.1 on 2021-01-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20210129_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosolicitud',
            name='pago_efectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pagoefectivo'),
        ),
        migrations.AlterField(
            model_name='pagosolicitud',
            name='pago_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pagotarjeta'),
        ),
        migrations.AlterField(
            model_name='pagosolicitud',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud'),
        ),
    ]
