# Generated by Django 3.1 on 2021-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20210129_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoefectivo',
            name='concepto',
            field=models.CharField(default='Solicitud', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='concepto',
            field=models.CharField(default='Solicitud', max_length=255, null=True),
        ),
    ]
