# Generated by Django 3.1 on 2021-01-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20210130_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoefectivo',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promocion'),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promocion'),
        ),
    ]
