# Generated by Django 3.1 on 2021-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20210130_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto2',
            field=models.ImageField(default=True, upload_to='categoria2'),
        ),
    ]
