# Generated by Django 3.1 on 2021-04-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_categoria_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rating',
            field=models.SmallIntegerField(default=4),
        ),
    ]
