# Generated by Django 3.1 on 2021-04-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_proveedor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=2),
        ),
    ]
