# Generated by Django 3.1 on 2021-04-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20210412_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
