# Generated by Django 3.1 on 2021-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='servicios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
