# Generated by Django 3.1 on 2021-05-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_proveedor_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_expiracion',
            field=models.DateTimeField(),
        ),
    ]
