# Generated by Django 3.1 on 2021-08-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20210524_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion_rating',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
