# Generated by Django 3.1 on 2021-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_solicitud_descripcion_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='codigo_invitacion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datos',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
