# Generated by Django 3.1 on 2021-08-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20210824_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='codigo_invitacion',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
