# Generated by Django 3.1 on 2021-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20210828_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_expiracion',
            field=models.CharField(max_length=200),
        ),
    ]
