# Generated by Django 3.1 on 2021-11-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_politicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='promociones'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_categoria',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
