# Generated by Django 3.1 on 2021-11-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20211031_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='apellidos',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='cedula',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='ciudad',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='nombres',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='planilla_servicios',
            field=models.ManyToManyField(to='api.Document'),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='telefono',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesion',
            name='servicio',
            field=models.ManyToManyField(to='api.Servicio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='document',
            field=models.ManyToManyField(to='api.Document'),
        ),
    ]
