# Generated by Django 3.1 on 2021-11-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20211107_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='ano_experiencia',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='planilla_servicios',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='tipo_cuenta',
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='apellidos',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='ciudad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='nombres',
            field=models.CharField(default='', max_length=255),
        ),
    ]
