# Generated by Django 3.1 on 2021-11-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20211109_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='estado',
        ),
    ]
