# Generated by Django 3.1 on 2021-11-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_remove_proveedor_pendiente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='telefono',
        ),
    ]
