# Generated by Django 3.1 on 2021-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20211109_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='cedula',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='telefono',
            field=models.CharField(default='', max_length=255),
        ),
    ]
