# Generated by Django 3.1 on 2021-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20211109_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='banco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='profesion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='tipo_cuenta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
