# Generated by Django 3.1 on 2021-11-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20211110_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='profesion',
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='banco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='tipo_cuenta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
