# Generated by Django 3.1 on 2021-11-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20211110_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='ano_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='profesion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
