# Generated by Django 3.1 on 2021-11-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20211110_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='planilla_servicios',
            field=models.ManyToManyField(to='api.Document'),
        ),
    ]
