# Generated by Django 3.1 on 2021-11-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_proveedor_pendiente_planilla_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='planilla_servicios',
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='planilla_servicios',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
