# Generated by Django 3.1 on 2021-11-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
