# Generated by Django 3.1 on 2021-11-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20211126_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
