# Generated by Django 3.1 on 2021-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_ciudad_disponible_cupon_cuponcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cupones',
            field=models.ManyToManyField(null=True, to='api.Cupon'),
        ),
    ]
