# Generated by Django 3.1 on 2021-12-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_insignia'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
