# Generated by Django 3.1 on 2021-12-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20211219_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
