# Generated by Django 3.1 on 2022-01-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_insignia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='codigo_invitacion',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='puntos',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
