# Generated by Django 3.1 on 2022-02-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20220104_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='promociones')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='datos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.planes'),
        ),
    ]
