# Generated by Django 3.1 on 2022-02-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20220224_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planes',
            new_name='Plan',
        ),
    ]
