# Generated by Django 3.1 on 2022-02-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20220224_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(upload_to='planes'),
        ),
    ]
