# Generated by Django 3.1 on 2022-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20220224_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.FloatField(),
        ),
    ]
