# Generated by Django 3.1 on 2022-02-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20220225_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes'),
        ),
    ]
