# Generated by Django 3.1 on 2022-02-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20220225_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='publicidad')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
