# Generated by Django 3.1 on 2022-03-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20220228_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_iniciacion',
            field=models.DateTimeField(null=True),
        ),
    ]
