# Generated by Django 3.1 on 2022-03-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_plan_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ano_profesion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='planilla_servicios',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='profesion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_cuenta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
