# Generated by Django 3.1 on 2022-03-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20220306_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicidad',
            old_name='foto',
            new_name='imagen',
        ),
    ]
