# Generated by Django 3.1 on 2022-03-09 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20220307_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
