# Generated by Django 3.1 on 2022-03-10 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20220309_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='fecha_iniciacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
