# Generated by Django 3.1 on 2022-03-11 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_cupon_fecha_iniciacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='direccion',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='genero',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
