# Generated by Django 3.1 on 2022-03-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_auto_20220311_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='licencia',
            field=models.CharField(default='', max_length=55),
        ),
    ]
