# Generated by Django 3.1 on 2022-03-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_proveedor_pendiente_licencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planproveedor',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_plan_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.planproveedor'),
        ),
    ]
