# Generated by Django 3.1 on 2022-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_auto_20220312_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='copiaCedula',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='proveedor_pendiente',
            name='genero',
            field=models.CharField(max_length=100),
        ),
    ]
