# Generated by Django 3.1 on 2022-03-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_proveedor_pendiente_copialicencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='planilla_servicios',
        ),
        migrations.CreateModel(
            name='Planilla_Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planilla', models.FileField(null=True, upload_to='planillas_proveedor')),
                ('idPendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor_pendiente')),
            ],
        ),
    ]
