# Generated by Django 3.1 on 2022-03-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_remove_proveedor_pendiente_plantilla_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planproveedor',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
