# Generated by Django 3.1 on 2022-03-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20220313_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planilla_Servicios',
        ),
    ]
