# Generated by Django 3.1 on 2022-03-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_auto_20220314_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planproveedor',
            old_name='idplan',
            new_name='plan',
        ),
    ]
