# Generated by Django 3.1 on 2022-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_auto_20220318_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMasiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('mensaje', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('ruta', models.CharField(max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='notificaciones-masivas')),
            ],
        ),
    ]
