# Generated by Django 3.1 on 2022-04-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_auto_20220406_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='profesiones',
        ),
        migrations.AddField(
            model_name='profesion_proveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ano_profesion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='profesion',
            field=models.CharField(default='', max_length=400),
        ),
    ]
