# Generated by Django 3.1 on 2022-04-07 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20220406_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProfesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=100)),
                ('anio_experiencia', models.PositiveIntegerField(default=0)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
        ),
    ]
