# Generated by Django 3.1 on 2022-04-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_solicitudprofesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprofesion',
            name='documento',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
