# Generated by Django 3.1 on 2022-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_solicitudprofesion_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprofesion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudprofesion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
