# Generated by Django 3.1 on 2022-04-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20220408_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('porcentaje', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='pago_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudprofesion',
            name='profesion',
            field=models.CharField(max_length=150),
        ),
    ]
