# Generated by Django 3.1 on 2022-04-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_auto_20220408_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Cargo',
        ),
    ]
