# Generated by Django 3.1 on 2022-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20220409_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprofesion',
            name='documento',
            field=models.FileField(null=True, upload_to='solicitudes'),
        ),
    ]
