# Generated by Django 3.1 on 2022-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20220409_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion_rating',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
