# Generated by Django 3.1 on 2022-04-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_auto_20220415_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='tipo_usuario',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
