# Generated by Django 3.1 on 2022-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_auto_20220416_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='cargo_banco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='cargo_paymentez',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='cargo_sistema',
            field=models.FloatField(default=0.0),
        ),
    ]
