# Generated by Django 3.1 on 2022-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_auto_20220422_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='planilla_servicios',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='copiaCedula',
            field=models.FileField(blank=True, null=True, upload_to='documentos-Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='copiaLicencia',
            field=models.FileField(blank=True, null=True, upload_to='documentos-Proveedor'),
        ),
    ]
