# Generated by Django 3.1 on 2022-04-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_auto_20220425_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion_proveedor',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
    ]
