# Generated by Django 3.1 on 2022-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_auto_20220425_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='prov_correo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='prov_telefono',
            field=models.CharField(default='0999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='promocion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
