# Generated by Django 3.1 on 2022-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_auto_20220501_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoefectivo',
            name='prov_correo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='prov_telefono',
            field=models.CharField(default='0999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='user_telefono',
            field=models.CharField(default='0999999999', max_length=15),
        ),
    ]
