# Generated by Django 3.1 on 2022-05-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_auto_20220502_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='correo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='usuario',
            field=models.CharField(default='', max_length=255),
        ),
    ]
