# Generated by Django 3.1 on 2022-05-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_tarjeta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='tipo',
        ),
    ]
