# Generated by Django 3.1 on 2022-05-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_tarjeta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='titulo',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
