# Generated by Django 3.1.14 on 2023-01-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_cargo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardauth',
            fields=[
                ('id_cardauth', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=20)),
                ('auth', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(default='', max_length=400),
        ),
    ]
