from django.contrib import admin

from django.contrib import admin
from api.models import *

# Register your models here.
admin.site.register(Categoria)
admin.site.register(Insignia)
admin.site.register(Suggestion)
admin.site.register(Servicio)
admin.site.register(Profesion)
admin.site.register(Profesion_Proveedor)
admin.site.register(Proveedor)
admin.site.register(Datos)
admin.site.register(Solicitud)
admin.site.register(Ubicacion)
admin.site.register(Tipo_Pago)
admin.site.register(Solicitante)
admin.site.register(Envio_Interesados)
admin.site.register(Document)
admin.site.register(Banco)
admin.site.register(Tipo_Cuenta)
admin.site.register(Cupon_Aplicado)
admin.site.register(Cuenta)
admin.site.register(Proveedor_Pendiente)
admin.site.register(Administrador)
admin.site.register(Notificacion)
admin.site.register(Tarjeta)
admin.site.register(Promocion)
admin.site.register(PromocionCategoria)
admin.site.register(Codigos)
admin.site.register(Cupon)
admin.site.register(CuponCategoria)
admin.site.register(PagoTarjeta)
admin.site.register(PagoEfectivo)
admin.site.register(PagoSolicitud)
admin.site.register(Plan)
admin.site.register(Publicidad)
admin.site.register(PlanProveedor)